### ISSUE TITLE
Lingua PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.lainsce.coin#1]
Lingua PT-BR does not work

**Comment by lainsce** [comment]
Please move issues about the app to its github repo: https://github.com/lainsce/coin

**Comment by nedrichards** [comment]
@lainsce as upstream, would you like us to close issues here? maybe put a readme pointing to the correct repo. @TingPing what do you think?

**Comment by lainsce** [comment]
A readme with friendly instructions about putting issues at the correct repo would be nice. :smile: 
Also, if there are issues posted here, you can close them for me, pointing at the correct repo link if doing so. :+1:
